language: r
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=release
    - RVERSION=devel

